name: EEG-Artifacts
channels:
  - anaconda
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - plotly
  - scikit-learn
  - pyyaml
  - pip
  - pip:
    - mne
    - edfio
    - mne-icalabel
    - torch
    - fire
    - pyEDFlib
    - hurst
    - antropy
    - nolds
    - xgboost
    - tqdm
    - saxpy
    - pathos
    - imbalanced-learn
    - mlflow
    - tensorboard
    - colortqdm
    - whittlehurst==1.1
    - yamvp==0.5
    - moabb
    - braindecode
    - huggingface_hub